pthread_test: pthread_test.c
		-gcc  -o $@ $^ -lpthread
		-./$@
		-rm $@

sum_sqr:02_sum_sqr.c
		-gcc  -o $@ $^ -lpthread
		-./$@
		-rm $@

sum_sqr_thread:02_sum_sqr_thread.c
		-gcc  -o $@ $^ -lpthread
		-./$@
		-rm $@

race_condition:04_race_condition.c
		-gcc  -o $@ $^ -lpthread
		-./$@
		-rm $@

mqueue:05_mqueue.c
		-gcc  -o $@ $^ -lpthread
		-./$@
		-rm $@